### ISSUE TITLE
Information missing in generated API docs

### ISSUE THREAD

**Issue by alexjj** [aumayr/beancount-docs-static#1] opened 2016-02-22 21:12 UTC
Whilst browsing the docs I noticed that some information was cut short on the docs-static site vs the underlying code:

e.g. API reference for [loader](https://github.com/aumayr/beancount-docs-static/blob/gh-pages/api_reference/beancount.loader.html#L229-L231) doesn't show anything after "Return type: A triple of"

Whereas the actual [module](https://github.com/aumayr/beancount-docs-static/blob/gh-pages/_modules/beancount/loader.html#L244-L248) info has extra information.

Visible from:
[API](https://aumayr.github.io/beancount-docs-static/api_reference/beancount.loader.html#beancount.loader.load_file) and [modules](https://aumayr.github.io/beancount-docs-static/_modules/beancount/loader.html#load_file).

There are several other functions where the returns a triple of is cut off on that page.

**Comment by aumayr** [comment] 2016-02-22 22:21
I think the problem is due to the format @blais did choose for the documentation:

```python
def load_file(filename, log_timings=None, log_errors=None, extra_validations=None,
              encoding=None):
    """Open a Beancount input file, parse it, run transformations and validate.

    Args:
      filename: The name of the file to be parsed.
      log_timings: A file object or function to write timings to,
        or None, if it should remain quiet.
      log_errors: A file object or function to write errors to,
        or None, if it should remain quiet.
      extra_validations: A list of extra validation functions to run after loading
        this list of entries.
      encoding: A string or None, the encoding to decode the input filename with.
    Returns:
      A triple of:
        entries: A date-sorted list of entries from the file.
        errors: A list of error objects generated while parsing and validating
          the file.
        options_map: A dict of the options parsed from the file.
    """
    # ...
```

Sphinx thinks that `A triple of:` is the name of the return value, as `filename:` is in the Args.

Fixing this would involve replacing every `A triple of:` with `A triple of` (removing the colon) in the Beancount source code.

**Comment by aumayr** [comment] 2016-02-22 22:21
I will test that and get back to you @alexjj

**Comment by aumayr** [comment] 2016-02-23 08:17
Relevant information can be found here: (Gist: this style of documentation for multiple return values, which technically they aren't, is not and will not be supported.)

https://bitbucket.org/birkenfeld/sphinx-contrib/issues/111/napoleon-multiple-returns-indentations

**Comment by aumayr** [comment] 2016-02-23 08:25
A way to document it would be like this:

```
    Returns:
      (entries, options_map, errors): A triple where the first value is a date-
        sorted list of entries from the file (entries), the second is a dict of
        the options parsed from the file (options_map) and the third is a list
        of error objects generated while parsing and validating the file
        (errors).
```

which renders like this:

![screenshot](https://cloud.githubusercontent.com/assets/5135450/13245663/f896baea-da0e-11e5-8a1a-56d88def350a.png)

It is not as good-looking in plain-text as the current solution, but renders better in Sphinx.

@blais Would it be OK if we change the few instances where this happens and submit a PR?

**Comment by blais** [comment] 2016-02-24 02:03
I'm happy to change (or for you to change) the docstrings to something slightly different in order to accommodate documentation generation. There's a lot of docstrings all over... I don't think I want to bother changing the style entirely of the whole codebase now. What you're suggesting sounds very reasonable to me, but I think it's incorrect: that parenthesized expression shows up in the slot for datatypes... Maybe we fiddle it better.

**Comment by blais** [comment] 2016-02-24 02:22
See 3becf158e398, where I made a change like I imagine could work.

**Comment by blais** [comment] 2016-02-24 03:48
Wrote  a script to find them: 
https://bitbucket.org/blais/beancount/src/c187fb01aab9380cdf56aaa14cfb3dbf8d55050a/experiments/find-multiline-returns.py?at=default&fileviewer=file-view-default

**Comment by aumayr** [comment] 2016-02-24 08:08
> See 3becf158e398, where I made a change like I imagine could work.

Looks good:

![screenshot2](https://cloud.githubusercontent.com/assets/5135450/13279139/b5f37684-dad5-11e5-9ce1-1b800c9a3e8b.png)

**Comment by aumayr** [comment] 2016-02-24 08:22
@alexjj This will be included when the documentation get's republished, so I am closing this. Again, thanks for the report!

**Closed by aumayr** 2016-02-24 08:22 UTC
Labels: bug
